Button_1_btn.clicked.connect(
                 function(){
                        print('1');
                     }
                 );
Button_2_btn.clicked.connect(
                 function(){
                        print('2');
                     }
                 );
Button_3_btn.clicked.connect(
                 function(){
                        print('3');
                     }
                 );
Button_4_btn.clicked.connect(
                 function(){
                        print('4');
                     }
                 );
Button_5_btn.clicked.connect(
                 function(){
                        print('5');
                     }
                 );
Button_6_btn.clicked.connect(
                 function(){
                        print('6');
                     }
                 );
Button_7_btn.clicked.connect(
                 function(){
                        print('7');
                     }
                 );
Button_8_btn.clicked.connect(
                 function(){
                        print('8');
                     }
                 );
Button_9_btn.clicked.connect(
                 function(){
                        print('9');
                     }
                 );
Button_10_btn.clicked.connect(
                 function(){
                        print('10');
                     }
                 );
Button_11_btn.clicked.connect(
                 function(){
                        print('11');
                     }
                 );
Button_12_btn.clicked.connect(
                 function(){
                        print('12');
                     }
                 );
Button_13_btn.clicked.connect(
                 function(){
                        print('13');
                     }
                 );
Button_14_btn.clicked.connect(
                 function(){
                        print('14');
                     }
                 );
Button_15_btn.clicked.connect(
                 function(){
                        print('15');
                     }
                 );
Button_16_btn.clicked.connect(
                 function(){
                        print('16');
                     }
                 );
Button_17_btn.clicked.connect(
                 function(){
                        print('17');
                     }
                 );
Button_18_btn.clicked.connect(
                 function(){
                        print('18');
                     }
                 );
Button_19_btn.clicked.connect(
                 function(){
                        print('19');
                     }
                 );
Button_20_btn.clicked.connect(
                 function(){
                        print('20');
                     }
                 );
Button_21_btn.clicked.connect(
                 function(){
                        print('21');
                     }
                 );
Button_22_btn.clicked.connect(
                 function(){
                        print('22');
                     }
                 );
Button_23_btn.clicked.connect(
                 function(){
                        print('23');
                     }
                 );
Button_24_btn.clicked.connect(
                 function(){
                        print('24');
                     }
                 );
Button_25_btn.clicked.connect(
                 function(){
                        print('25');
                     }
                 );
Button_26_btn.clicked.connect(
                 function(){
                        print('26');
                     }
                 );
Button_27_btn.clicked.connect(
                 function(){
                        print('27');
                     }
                 );
Button_28_btn.clicked.connect(
                 function(){
                        print('28');
                     }
                 );
Button_29_btn.clicked.connect(
                 function(){
                        print('29');
                     }
                 );
Button_30_btn.clicked.connect(
                 function(){
                        print('30');
                     }
                 );
Button_31_btn.clicked.connect(
                 function(){
                        print('31');
                     }
                 );
Button_32_btn.clicked.connect(
                 function(){
                        print('32');
                     }
                 );
Button_33_btn.clicked.connect(
                 function(){
                        print('33');
                     }
                 );
Button_34_btn.clicked.connect(
                 function(){
                        print('34');
                     }
                 );
Button_35_btn.clicked.connect(
                 function(){
                        print('35');
                     }
                 );
Button_36_btn.clicked.connect(
                 function(){
                        print('36');
                     }
                 );
Button_37_btn.clicked.connect(
                 function(){
                        print('37');
                     }
                 );
Button_38_btn.clicked.connect(
                 function(){
                        print('38');
                     }
                 );
Button_39_btn.clicked.connect(
                 function(){
                        print('39');
                     }
                 );
Button_40_btn.clicked.connect(
                 function(){
                        print('40');
                     }
                 );
Button_41_btn.clicked.connect(
                 function(){
                        print('41');
                     }
                 );
Button_42_btn.clicked.connect(
                 function(){
                        print('42');
                     }
                 );
