#############################################################################
# Makefile for building: IDE
# Generated by qmake (2.01a) (Qt 4.8.0) on: ??? ??? 25 17:00:25 2013
# Project:  IDE.pro
# Template: subdirs
# Command: c:\qtsdk\desktop\qt\4.8.0\mingw\bin\qmake.exe -spec c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile IDE.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qtsdk\desktop\qt\4.8.0\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-BST_DISPLAY

BST_DISPLAY\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) BST_DISPLAY\ $(MKDIR) BST_DISPLAY\ 
	cd BST_DISPLAY\ && $(QMAKE) d:\MyProject\IDE\BST_DISPLAY\BST_DISPLAY.pro -spec c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-BST_DISPLAY-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) BST_DISPLAY\ $(MKDIR) BST_DISPLAY\ 
	cd BST_DISPLAY\ && $(QMAKE) d:\MyProject\IDE\BST_DISPLAY\BST_DISPLAY.pro -spec c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-BST_DISPLAY: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE)
sub-BST_DISPLAY-make_default: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) 
sub-BST_DISPLAY-make_first: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) first
sub-BST_DISPLAY-all: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) all
sub-BST_DISPLAY-clean: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) clean
sub-BST_DISPLAY-distclean: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) distclean
sub-BST_DISPLAY-install_subtargets: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) install
sub-BST_DISPLAY-uninstall_subtargets: BST_DISPLAY\$(MAKEFILE) FORCE
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: IDE.pro  c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++/qmake.conf c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/qconfig.pri \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/modules/qt_webkit_version.pri \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_functions.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_config.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/exclusive_builds.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_pre.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_pre.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug_and_release.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_post.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_post.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/declarative_debug.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/rtti.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/exceptions.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/stl.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/shared.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/warn_on.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/thread.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/moc.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/windows.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/resources.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/uic.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/yacc.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/lex.prf \
		c:/QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile IDE.pro
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\qconfig.pri:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\modules\qt_webkit_version.pri:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt_functions.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt_config.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\exclusive_builds.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\default_pre.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\default_pre.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\debug.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\debug_and_release.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\default_post.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\default_post.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\declarative_debug.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\rtti.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\exceptions.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\stl.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\shared.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\warn_on.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\thread.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\moc.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\windows.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\resources.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\uic.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\yacc.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\lex.prf:
c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile IDE.pro

qmake_all: sub-BST_DISPLAY-qmake_all FORCE

make_default: sub-BST_DISPLAY-make_default FORCE
make_first: sub-BST_DISPLAY-make_first FORCE
all: sub-BST_DISPLAY-all FORCE
clean: sub-BST_DISPLAY-clean FORCE
distclean: sub-BST_DISPLAY-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-BST_DISPLAY-install_subtargets FORCE
uninstall_subtargets: sub-BST_DISPLAY-uninstall_subtargets FORCE

sub-BST_DISPLAY-sub_Debug: BST_DISPLAY\$(MAKEFILE)
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-BST_DISPLAY-sub_Debug

sub-BST_DISPLAY-sub_Release: BST_DISPLAY\$(MAKEFILE)
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) release
release: sub-BST_DISPLAY-sub_Release

sub-BST_DISPLAY-check: BST_DISPLAY\$(MAKEFILE)
	cd BST_DISPLAY\ && $(MAKE) -f $(MAKEFILE) check
check: sub-BST_DISPLAY-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

